### ISSUE TITLE
Add option for different notification types

### ISSUE THREAD

**Issue by macmule** [dataJAR/jamJAR#14]
Alert types for “oh we installed something”

Banner types for “oh hey, log out”

Maybe using Yo for the latter.

**Comment by macmule** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [jamJAR - Add option for different notification types](https://trello.com/c/PORcODsP/22-jamjar-add-option-for-different-notification-types)

**Comment by apizz** [comment]
To add on to this, but perhaps warrants a separate issue, I wondered if there might be a way since we're figuring out the status of an install if there might be an alert for when software is downloaded but a blocking app is open.

I understand this is typically handled by 'Logout', but wonder if that's really necessary just for an app like Chrome or Firefox, which is just drag and drop.  As an example, we've had a number of users install something like Adobe Acrobat through Self Service but they didn't read the forcibly displayed description that indicates Microsoft Word has to be closed.

Could there be a separate alert box that would present an option to either "Quit & Install" which would quit the running blocking app(s) or "Install Later"?

**Comment by macmule** [comment]
That would be separate, but [https://github.com/dataJAR/jamJAR/wiki/jamJAR-Preferences#notifier_msg_pending](https://github.com/dataJAR/jamJAR/wiki/jamJAR-Preferences#notifier_msg_pending)

thats what that’s for
the new notifier will present that as an alert vs a banner

**Comment by TSPARR** [comment]
I think what @apizz is saying is that it for some clients it seems a lot to ask someone to completely logout to finish installing a Chrome update when maybe they could be prompted to quit Chrome, have it update, and be on their way. Now realistically, they could just logout at the end of the day and be done with it, but maybe by that time they've forgotten/dismissed the alert/what have you.

Wrapping some additional UI/UX around it and giving them the option to get it done within their current working session would have some good benefits I think. Though I totally understand if you're not particularly motivated to add it if you don't see the benefits for your needs.

**Comment by macmule** [comment]
If you send the sender_id & are using terminal-notifier.. or the newer notifier app we're finalising.. & the suer clicks the message.. then Managed Software Center launches which then advises _exactly_ why Munki cannot install at that time.

And, this "issue" was for a category that we just don't alert on.. for installing tools etc that the end user need not know about.

**Comment by macmule** [comment]
In 1.5, notifier to come
