### ISSUE TITLE
Comma Separated "Add to Installs"

### ISSUE THREAD

**Issue by MrTreger** [dataJAR/jamJAR#34]
When adding multiple items to "Add to Installs" with comma separated values multiple notifications pop up for each app that is being installed, I have attached a screenshot for reference.

If I can assist with more info let me know

Thanks

Louis
![IMG_9159](https://user-images.githubusercontent.com/78492267/106767422-c0901c80-6632-11eb-921b-cfd8db0524c6.JPG)

**Comment by apizz** [comment]
Would need to see how you have your Jamf policy setup, macOS version and jamJAR version.  I know at last co. I had this working just fine w/ no duplicate notifications.  Granted not sure if this is unique to the OS version, so the more detail you can provide as to your setup would be infinitely easier to troubleshoot.  Because IMO the notification functionality works as expected, so why your setup is producing duplicates and not others would be the question needing answering.

**Comment by MrTreger** [comment]
Ok, no worries,

I have seen this pop up from time to time on older OS versions but in the interests of keeping this simple for now will focus on the current device I am using and seeing the errors. FYI its not a showstopper or anything just something I noticed.

macOS version is 11.2 (Catalina seems to be ok - am running some builds now an they appear fine)
jamJAR version is 2.0.1 (updated today)
Screenshot of policy is attached

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/78492267/106773735-5038c980-6639-11eb-8053-ca676cfeeacf.png">

Let me know if there is more I can provide. or something more specific in the policy you want to see

**Comment by macmule** [comment]
I'm closing this off.. not to dismiss.. but #36's title is clearer :)
